Warning: incomplete final line found on '/Users/maria/PS446/yeung_replication_files/analysis_experiment.R' 

[1] "Warning: `geom_errobarh()` was deprecated in ggplot2 4.0.0."                 
[2] "Warning: Please use the `orientation` argument of `geom_errorbar()` instead."

[1] "Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0."
[2] "Warning: Please use `linewidth` instead."                                  

